#!/bin/bash

# expects environment structure
# dir/
# ├── share/
# |   └── luajit-2.1.0-beta3/
# |       └── ..lua_packages..
# └── lib/
#     └── libluajit.so.2

if [ $# -lt 2 ]
then
    echo "usage $0 dir exe [args...]"
    exit 1
fi

export LUA_PATH="$1/share/luajit-2.1.0-beta3/?.lua;$1/src/lua/?.lua"
export LUA_CPATH="$1/lib/?.so;$1/src/?.so"

exec $2 ${@:3}
